export const subcategories = [
  { title: "Стулья", categoriesId: 1 },
  { title: "Столы", categoriesId: 1 },
  { title: "Уголки", categoriesId: 1 },
  { title: "Барные стулья", categoriesId: 1 },
  { title: "Диваны", categoriesId: 1 },
  { title: "Кровати", categoriesId: 2 },
  { title: "Освещение", categoriesId: 2 },
  { title: "Стеллажи", categoriesId: 2 },
  { title: "Шкафы", categoriesId: 2 },
  { title: "Камины", categoriesId: 3 },
  { title: "Книжные шкафы", categoriesId: 3 },
  { title: "Комоды", categoriesId: 3 },
  { title: "Диваны", categoriesId: 3 },
  { title: "Стелажи", categoriesId: 3 },
  { title: "Тумбы для обуви", categoriesId: 4 },
  { title: "Шкафы", categoriesId: 4 },
  { title: "Зеркала", categoriesId: 4 },
  { title: "Диваны", categoriesId: 4 },
  { title: "Письменные столы", categoriesId: 5 },
  { title: "Шкафы", categoriesId: 5 },
  { title: "Компьютерные кресла", categoriesId: 5 },
  { title: "Кроватки", categoriesId: 6 },
  { title: "Стульчики для кормления", categoriesId: 6 },
  { title: "Манежи", categoriesId: 6 },
  { title: "Колыбели", categoriesId: 6 },
];
